# Connection to Render PostgreSQL (Oregon Region)
spring.datasource.url=jdbc:postgresql://dpg-d7u8263bc2fs73f73f4g-a.oregon-postgres.render.com:5432/g8_fitness_db
spring.datasource.username=g8_fitness_db_user
spring.datasource.password=bePPrvHb7fT2yYvWLBa63wIJ9iJJFpn0

# Database Logic & Logging
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver